# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-demo
  labels:
    app: log-demo
spec:
  selector:
    matchLabels:
      app: log-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: log-demo
    spec:
      containers:
        - name: log-demo
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            [
              "while true; do echo 'Kubetail test logs from pod log-demo'; sleep 2; done",
            ]
