name: ci

permissions:
  contents: read

on:
  push:
    branches:
      - E2E-exp

jobs:
  # build:
  #   name: Build binaries
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-24.04
  #         # - ubuntu-24.04-arm
  #         # - macos-latest
  #         # - macos-13
  #         # - windows-latest
  #       include:
  #         - os: ubuntu-24.04
  #           GOOS: linux
  #           GOARCH: amd64
  #         # - os: ubuntu-24.04-arm
  #         #   GOOS: linux
  #         #   GOARCH: arm64
  #         # - os: macos-latest
  #         #   GOOS: darwin
  #         #   GOARCH: arm64
  #         # - os: macos-13
  #         #   GOOS: darwin
  #         #   GOARCH: amd64
  #         # - os: windows-latest
  #         #   GOOS: windows
  #         #   GOARCH: amd64
  #         # - os: windows-11-arm
  #         #   GOOS: windows
  #         #   GOARCH: arm64
  #   runs-on: ${{ matrix.os }}
  #   outputs:
  #     artifacts: ${{ steps.upload.outputs.artifact-names }}
  #   steps:
  #     - name: Get tag name
  #       uses: olegtarasov/get-tag@2.1.3
  #       id: tagName
  #       with:
  #         tagRegex: "cli/v(.*)"
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #     - uses: pnpm/action-setup@v4
  #       with:
  #         version: 10
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.24.3"
  #         cache: false
  #     - name: Run build script
  #       run: make build VERSION=${{ steps.tagName.outputs.tag }}

  e2e-test:
    # needs: build
    runs-on: ubuntu-24.04
    steps:
      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: bin
      #     pattern: artifacts-${{ matrix.os }}-${{ matrix.arch }}
      #     merge-multiple: true
      - name: Setup k3s cluster using k3d
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "kubetail-test-cluster"
          args: --agents 1
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.33.1

      - name: Verify kubectl and k3s cluster is running
        run: |
          kubectl get pods
          cat $HOME/.kube/config
