name: publish-win

on:
  release:
    types:
      - published

jobs:
  winget-release:
    name: Release on winget
    runs-on: ubuntu-24.04
    steps:
      - name: Download sha256 files
        id: release-info
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "kubetail-windows*zip.sha256"

      - name: Sparse checkout only manifests
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/manifests
          sparse-checkout-cone-mode: false
          fetch-depth: 1
          path: winget-manifests

      - name: Clone the winget packages repo
        uses: actions/checkout@v4
        with:
          repository: victorchrollo14/winget-pkgs
          token: ${{ secrets.GH_TOKEN }}
          path: winget-pkgs

      # - name: Get Release info
      #   id: release-info
      #   run: |
      #     VERSION="${{ github.event.release.tag_name }}"
      #     echo "tag=${VERSION#cli/v}" >> $GITHUB_OUTPUT
      #     echo "release_name=${{ github.event.release.name }}" >> $GITHUB_OUTPUT
      #     echo "release_body=${{ github.event.release.body }}" >> $GITHUB_OUTPUT

      - name: Extract tags and sha
        id: meta
        run: |
          pwd
          ls -la
          ls -la ./winget-manifests
          echo 'tag_name = ${{ steps.release-info.outputs.tag_name }}'
          AMD64_SHA=$( cat ./kubetail-windows-amd64.zip.sha256 )
          ARM64_SHA=$( cat ./kubetail-windows-arm64.zip.sha256 )
          TAG_NAME="${{ steps.release-info.outputs.tag_name }}"

          # git fetch --tags
          # PREV_TAG=$(git tag --sort=-creatordate | grep '^cli/v' | sed -n '2p')

          # echo "prev_tag=${PREV_TAG#cli/v}" >> $GITHUB_OUTPUT
          echo "tag=${TAG_NAME#cli/v}" >> $GITHUB_OUTPUT
          echo "amd64_sha=$AMD64_SHA" >> $GITHUB_OUTPUT
          echo "arm64_sha=$ARM64_SHA" >> $GITHUB_OUTPUT

      - name: Update winget release
        run: |
          NEW_FOLDER='./winget-pkgs/manifests/k/Kubetail/Kubetail/${{ steps.meta.outputs.tag }}'
          mkdir -p "$NEW_FOLDER"

          # better to update before copying and then we can make the pr
          cp ./winget-manifests/.github/manifests/* "$NEW_FOLDER"/ 
          ls -la "$NEW_FOLDER"
